<?php

namespace Database\Seeders;

use App\Models\roles;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class RoleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        roles::truncate();

        $roles = [
            "2" => "Dashboard",
            "3" => "Enrollment Module",
            "4" => "Application Confirmation (Enrollment Module)",
            "5" => "Courses Module",
            "6" => "All Courses (Courses Module)",
            "7" => "Instructor Management Module",
            "8" => "Instructor List (Instructor Management Module)",
            "9" => "Billing Module",
            "10" => "Bank Accounts Management (Billing Module)",
            "11" => "Billing Monitoring (Billing Module)",
            "12" => "Billing Logs (Billing Module)",
            "13" => "Price Matrix (Billing Module)",
            "14" => "Report Module",
            "15" => "PDE Module",
            "16" => "Request PDE (PDE Module)",
            "17" => "PDE Status (PDE Module)",
            "18" => "PDE Report (PDE Module)",
            "19" => "Maintenance Module",
            "20" => "Announcement (Maintenance Module)",
            "21" => "FAQ (Maintenance Module)",
            "22" => "Handout (Maintenance Module)",
            "23" => "Rank (Maintenance Module)",
            "24" => "Roles (Maintenance Module)",
            "25" => "Room (Maintenance Module)",
            "26" => "Course Department (Maintenance Module)",
            "27" => "Home Page (Maintenance Module)",
            "28" => "Company (Maintenance Module)",
            "29" => "Certificate (Maintenance Module)",
            "30" => "Communication Module",
            "31" => "Text Blast (Communication Module)",
            "32" => "Send Email (Communication Module)",
            "33" => "Inquiries (Communication Module)",
            "34" => "Trainees Module",
            "35" => "Manage Trainees (Trainees Module)",
            "36" => "Trainee Inquiries (Trainees Module)",
            "37" => "Admin Accounts Module",
            "38" => "Manage Accounts (Admin Accounts Module)",
            "39" => "Training Calendar Module",
            "40" => "Training Schedule (Training Calendar Module)",
            "41" => "Special Class (Training Calendar Module)",
            "42" => "Event logs",
            "43" => "Notification History",
            "44" => "Pde Maintenance (PDE Module)",
            "45" => "Remedial (Enrollment Module)",
            "46" => "Logs (Enrollment Module)",
            "47" => "Manage Reservation",
            "48" => "Check In (Manage Reservation Module)",
            "49" => "Check Out (Manage Reservation Module)",
            "50" => "No Show (Manage Reservation Module)",
            "51" => "Room Assignment Report (Manage Reservation Module)",
            "52" => "Waiver-Amenities Checklist (Manage Reservation Module)",
            "53" => "Check Out List (Manage Reservation Module)",
            "54" => "Room Price Maintenance (Manage Reservation Module)",
            "55" => "Edit Vessel (Billing Module)",
            "56" => "Attach Signature_BS_Staff (Billing Module)",
            "57" => "Attach Signature_BOD_MGR(Billing Module)",
            "58" => "Attach Signature_GM (Billing Module)",
            "59" => "View Attachment (Billing Module)",
            "60" => "Add Attachment (Billing Module)",
            "61" => "Update Billing Status (Billing Module)",
            "62" => "Pending Statements Board (Billing Module)",
            "63" => "Billing Statement Review Board (Billing Module)",
            "64" => "Finance Review Board (Billing Module)",
            "65" => "BOD Manager Review Board (Billing Module)",
            "66" => "GM Review Board (Billing Module)",
            "67" => "BOD Manager Dispatch Board (Billing Module)",
            "68" => "Client Confirmation Board (Billing Module)",
            "69" => "Proof of Payment Upload Board (Billing Module)",
            "70" => "Official Receipt Issuance Board (Billing Module)",
            "71" => "Official Receipt Confirmation Board (Billing Module)",
            "72" => "Transaction Close Board (Billing Module)",
            "73" => "Start Process (Billing Module)",
            "74" => "Generate Billing Statement(Billing Module)",
            "75" => "PDE Maintenance (PDE Module)",
            "76" => "Dashboard (Company Profile)",
            "77" => "Enrollment (Company Profile)",
            "78" => "Application Confirmation (Company Profile - Enrollment)",
            "79" => "View Trainees (Company Profile - Enrollment)",
            "80" => "Handout Password (Company Profile)",
            "81" => "Billing (Company Profile)",
            "82" => "PDE (Company Profile)",
            "83" => "Request PDE (Company Profile - PDE)",
            "84" => "PDE Status (Company Profile - PDE)",
            "85" => "Edit Profile (Company Profile)",
            "86" => "Vessel Management (Billing Module)",
            "87" => "View Trainee List (Dormitory Module)",
            "88" => "Send Back (Billing Module)",
            "89" => "ATD / SLAF (Billing Module)",
            "90" => "Check In Scanner (Dormitory Module)",
            "91" => "Check Out Scanner (Dormitory Module)",
            "92" => "Events Logs (Dormitory Module)",
            "93" => "Room Capacity Maintenance (Dormitory Module)",
            "94" => "Exchange Rate(Billing Module)",
            "95" => "Update Exchange Rate(Billing Module)",
            "96" => "JISS Billing (JISS Billing)",
            "97" => "JISS Pending Statements Board (JISS Billing)",
            "98" => "JISS Billing Statement Review Board (JISS Billing)",
            "99" => "JISS BOD Manager Review Board (JISS Billing)",
            "100" => "JISS GM Review Board (JISS Billing)",
            "101" => "JISS BOD Manager Review Board (JISS Billing)",
            "102" => "JISS Client Confirmation Board (JISS Billing)",
            "103" => "JISS Proof of Payment Upload Board (JISS Billing)",
            "104" => "JISS Email Maintenance (JISS Billing)",
            "105" => "PDE Billing Dashboard (PDE Billing)",
            "106" => "JISS Transaction Close Board (JISS Billing)",
            "107" => "Bus Mobile Scanner",
            "108" => "Meal Monitoring",
            "109" => "Billing JISS Module",
            "110" => "Certificate Approval Module",
            "111" => "For Approval Module (Certificate Approval Module)",
            "112" => "Releasing Certificates (Certificate Approval Module)",
            "113" => "Reports (Manage Reservation Module)",
            "114" => "JISS Company Maintenance (JISS Billing)",
            "115" => "JISS Course Maintenance (JISS Billing)",
            "116" => "JISS Price Matrix (JISS Billing)",
            "117" => "JISS Maintenance (JISS Billing)",
            "118" => "Released Certificates (Certificate Approval Module)",
            "119" => "Delete Attachment (Billing Module)",
            "120" => "JISS Add Billing Data (JISS Billing)",
            "121" => "JISS Approver 1 (JISS Billing)",
            "122" => "JISS Approver 2 (JISS Billing)",
            "123" => "Dormitory Change Dorm Type (Dormitory Module)",
            "124" => "Company Manage Instructor (PRPD Module)",
            "125" => "Dashboard",
            "126" => "Billed Marker (Billing Module)",
            "127" => "See Details (Billing Module)",
            "128" => "Forward Billing (Billing Module)",
            "129" => "Payroll (Payroll Module)",
            "130" => "Biometrics (Payroll Module)",
            "131" => "Generate Payroll (Payroll Module)",
            "132" => "Instructor Rate (Payroll Module)",
            "133" => "Rate Maintenance (Payroll Module)",
            "134" => "Enrollment (Company Module)",
            "135" => "Handout Password (Company Module)",
            "136" => "Billing (Company Module)",
            "137" => "PDE (Company Module)",
            "138" => "Edit Company Profile (Company Module)",
            "139" => "File Overtime (Instructor Module)",
            "140" => "Approval of Overtime Profile (Instructor Module)",
            "141" => "Search Billing Schedule (Billing Module)",
            "142" => "Archive Billing (Billing Module)",
            "143" => "Failure Time In / Time Out Approval (Instructor Module)",
            "144" => "Pde Maintenance Company (PDE Module)",
            "145" => "Pde Billig Data Preparation(PDE Billing)",
            "146" => "Pde Billing Generation(PDE Billing)",
            "147" => "Manager Review Board (PDE Billing)",
            "148" => "GM Review Board (PDE Billing)",
            "149" => "Bod Manager Dispatch Board (PDE Billing)",
            "150" => "Client Confirmation Board (PDE Billing)",
            "151" => "Client Confirmation Board (PDE Billing)",
            "152" => "Proof Payment Board (PDE Billing)",
            "153" => "Official Receipt Issuance Board (PDE Billing)",
            "154" => "Transaction Closed Board (PDE Billing)",
            "155" => "Certificate Viewer (Company Module)",
            "156" => "JISS Approver 3 (JISS Billing)",
            "157" => "Export Trainee WiFi Password",
            "158" => "Transfer Billing (Billing Module)",
            "159" => "Admin Upload POP (Billing Module)",
            "160" => "Admin Confirm Client Board (Billing Module)",
            "161" => "Admin Confirm OR Client Board (Billing Module)",
            "162" => "All Billing Type (Billing Module)",
            "163" => "JISS Billing (Billing Module)",
            "164" => "Standard Billing (Billing Module)",
        ];


        foreach ($roles as $id => $role_name) {
            roles::create([
                'id' => $id,
                'rolename' => $role_name
            ]);
        }
    }
}
