<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Attendance-Report-{{$time}}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <style type="text/css">
        @page {
            margin: 100px 25px;
        }

        body {
            font-family: 'Arial', sans-serif;
            font-size: 8pt;
            line-height: 1;
            background-color: #f8f9fa;
            color: #333;
        }

        header {
            position: fixed;
            top: -60px;
            left: 0;
            right: 0;
            height: 50px;
            text-align: center;
            border-bottom: 1px solid #ddd;
            padding-bottom: 10px;
        }

        footer {
            position: fixed;
            bottom: -60px;
            left: 0;
            right: 0;
            height: 30px;
            text-align: center;
            font-size: 9pt;
            color: #777;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }

        .pagenum:before {
            content: counter(page);
        }

        .logo-container {
            text-align: center;
            margin-bottom: 20px;
        }

        .logo-container img {
            max-width: 150px;
            height: auto;
        }

        .report-title {
            font-size: 18pt;
            font-weight: bold;
            text-align: center;
            margin-bottom: 20px;
            color: #2c3e50;
        }

        .report-subtitle {
            font-size: 12pt;
            text-align: center;
            margin-bottom: 30px;
            color: #34495e;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
            background-color: #fff;
            box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
        }

        th,
        td {
            border: 1px solid #e0e0e0;
            padding: 8px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
            font-weight: bold;
            text-transform: uppercase;
            font-size: 9pt;
            color: #2c3e50;
        }

        tr:nth-child(even) {
            background-color: #f8f9fa;
        }

        .instructor-name {
            font-size: 14pt;
            font-weight: bold;
            margin-top: 30px;
            margin-bottom: 10px;
            color: #2c3e50;
            border-bottom: 2px solid #3498db;
            padding-bottom: 5px;
        }

        .no-data {
            text-align: center;
            font-style: italic;
            color: #777;
            padding: 20px;
        }
    </style>
</head>

<body>
    <header>
        <div class="logo-container">
            <img src="{{ public_path('assets/images/oesximg/NETI.png') }}" alt="NETI Logo">
        </div>
    </header>

    <footer>
        <table class="w-100">
            <tr>
                <td style="width:70%; border: none;">
                    <small><i>This document is system generated. (Generated by: {{$g_user->formal_name()}})</i></small>
                </td>
                <td class="text-right" style="width:30%; border: none;">
                    <small><i>Page <span class="pagenum"></span></i></small>
                </td>
            </tr>
        </table>
    </footer>

    <main>
        <div class="report-title">ATTENDANCE OF GUEST LECTURERS</div>
        <div class="report-subtitle">
            Period: {{ date('F d, Y', strtotime($period_start)) }} - {{ date('F d, Y', strtotime($period_end)) }}<br>
            Generated on: {{ date('F d, Y', strtotime($time)) }}
        </div>

        @foreach($users as $user)
        @php
        $attendances = $user->instructor_time_log()->whereBetween('created_date', [$period_start, $period_end])->where('status', 2)->orderBy('created_date', 'asc')->get();
        @endphp

        @if($attendances->count() > 0)
        <div class="instructor-name">
            {{optional(optional($user->instructor)->rank)->rankacronym}} {{$user->formal_name()}}
        </div>
        <table>
            <thead>
                <tr>
                    <th>Course Code</th>
                    <th>Date</th>
                    <th>Time-In</th>
                    <th>Time-Out</th>
                    <th>Date Approved</th>
                    <th>Remarks</th>
                </tr>
            </thead>
            <tbody>
                @foreach($attendances as $attendance)
                <tr>
                    <td><i>{{optional($attendance->course)->FullCourseName ?? 'NO ASSIGNMENT COURSE'}}</i></td>
                    <td>{{ date('M d, Y', strtotime($attendance->created_date)) }}</td>
                    <td>{{ date('h:i A', strtotime($attendance->time_in)) }}</td>
                    <td>{{ date('h:i A', strtotime($attendance->time_out)) }}</td>
                    <td>{{ date('M d, Y', strtotime($attendance->created_at)) }}</td>
                    <td><i>{{ optional($attendance->approved_remarks)->first_name }} {{ optional($attendance->approved_remarks)->last_name }}</i></td>
                </tr>
                @endforeach
            </tbody>
        </table>
        @endif
        @endforeach
    </main>
</body>

</html>