<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Instructor Payroll</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <style type="text/css">
        body {
            margin-bottom: 20px;
            font-size: 10pt;
            font-family: Verdana, Arial, sans-serif;
            background-repeat: no-repeat;
            background-position: center center;
            background-size: cover;
        }

        table {
            font-size: x-small;
            width: 100%;
        }

        tfoot tr td {
            font-weight: bold;
            font-size: x-small;
        }

        .gray {
            background-color: lightgray;
        }

        header {
            position: fixed;
            top: 0;
            left: 0;
            right: 0;
            height: 70px;
            text-align: center;
        }

        footer {
            position: fixed;
            bottom: 0;
            left: 0;
            right: 0;
            height: 20px;
            text-align: center;
        }

        .pagenum:before {
            content: counter(page);
        }

        .logo-container {
            text-align: center;
            margin-bottom: 20px;
        }

        .logo-container img {
            max-width: 30%;
            height: auto;
            display: inline-block;
        }

        .company-info pre {
            margin: 0;
        }

        th,
        .border-td {
            border: 1px solid black;
        }

        th {
            text-align: left;
            background-color: lightgray;
        }

        td {
            /* background-color: white; */
            padding: 4px;
        }

        thead tr {
            page-break-inside: avoid;
            /* Prevent header from breaking across pages */
        }

        .col-30 {
            width: 30%;
        }

        .col-5 {
            width: 5%;
        }

        .col-60 {
            width: 60%;
        }

        .col-10 {
            width: 10%;
        }

        .col-15 {
            width: 15%;
        }

        @page {
            /* margin-top: 2cm; */
            /* Set a margin-top for every page */
        }

        @page :first {
            margin-top: 0;
            /* Remove margin-top for the first page */
        }
    </style>

</head>

<body>
    <footer class="w-100">
        <table class="w-100">
            <tr>
                <td style="width:70%">
                    <small><i>This document is system generated.
                            (Generated by: {{$user->formal_name()}})</i></small>
                </td>
            </tr>
        </table>
    </footer>

    <div class="logo-container">
        <img src="{{ public_path('assets/images/oesximg/NETI.png') }}" alt="">
    </div>
    <div style="page-break-inside: avoid;">
        <table style="font-size: 6pt; width: 100%;">
            <thead>
                <tr>
                    <th class="border-td" colspan="12" style="text-transform: uppercase; font-weight: bold; text-align: center;">INSTRUCTOR PAYROLL HISTORY</th>
                </tr>
                <tr style="text-align: center;">
                    <th style="text-align: center;">MEMO NUMBER</th>
                    <th style="text-align: center;">NAME OF INSTRUCTOR</th>
                    <th style="text-align: center;">RANK</th>
                    <th style="text-align: center;">ASSIGNMENT / COURSE CONDUCTED</th>
                    <th style="text-align: center;">DATE COVERED</th>
                    <th style="text-align: center;">NO. OF DAYS</th>
                    <th style="text-align: center;">NO. OF HR/OT</th>
                    <th style="text-align: center;">TIN</th>
                    <th style="text-align: center;">RATE PER DAY</th>
                    <th style="text-align: center;">RATE PER HOUR</th>
                    <th style="text-align: center;">SUBTOTAL</th>
                    <th style="text-align: center;">TOTAL</th>
                </tr>
            </thead>
            <tbody>
                @php
                $previousUser = null;
                $userTotal = 0;
                @endphp
                @foreach ($payrolls as $index => $payroll)
                <tr style="page-break-inside: avoid;">
                    <td class="border-td">{{ $payroll->payroll_period->memo_num }}</td>
                    @if ($index === 0 || $payroll->user->formal_name() !== $payrolls[$index - 1]->user->formal_name())
                    <td class="border-td text-center" style="text-transform: uppercase; font-weight: bold;" rowspan="{{ $payrolls->where('user_id', $payroll->user_id)->count() }}">{{ $payroll->user->formal_name() }}</td>
                    @endif
                    <td class="border-td" style="text-transform: uppercase; font-weight: bold; text-align: center;">{{ $payroll->user->instructor->rank->rank }}</td>
                    <td class="border-td" style="text-transform: uppercase;">
                        @if($payroll->course_id && $payroll->description_id)
                        {{ optional($payroll->payrolldesc)->description }}
                        @elseif(optional($payroll)->course_id)
                        {{ $payroll->course->coursecode }} - {{ $payroll->course->coursename }}
                        @elseif(optional($payroll)->description_id)
                        {{ $payroll->payrolldesc->description }}
                        @endif
                    </td>
                    <td class="border-td" style="text-transform: uppercase; text-align: center;">
                        @php
                        $dates = json_decode($payroll->date_record);
                        sort($dates);
                        $formattedDates = [];

                        $startDate = null;
                        $endDate = null;

                        foreach ($dates as $date) {
                        if ($startDate === null) {
                        $startDate = $date;
                        $endDate = $date;
                        } elseif (strtotime($date) == strtotime("+1 day", strtotime($endDate))) {
                        $endDate = $date;
                        } else {
                        if ($startDate == $endDate) {
                        $formattedDates[] = date('d M', strtotime($startDate));
                        } else {
                        $formattedDates[] = date('d', strtotime($startDate)) . '-' . date('d M', strtotime($endDate));
                        }
                        $startDate = $date;
                        $endDate = $date;
                        }
                        }

                        if ($startDate == $endDate) {
                        $formattedDates[] = date('d M', strtotime($startDate));
                        } else {
                        $formattedDates[] = date('d', strtotime($startDate)) . '-' . date('d M', strtotime($endDate));
                        }

                        $formattedDateRange = implode(', ', $formattedDates);
                        echo $formattedDateRange;
                        @endphp
                    </td>
                    <td class="border-td" style="text-align: center;">{{ $payroll->no_day }}</td>
                    <td class="border-td" style="text-align: center;">{{ $payroll->no_ot }}</td>
                    <td class="border-td" style="text-align: center; min-width: 60px;">
                        @if (optional($payroll->user->instructor)->tin)
                        {{ optional($payroll->user->instructor)->tin }}
                        @else
                        ---------
                        @endif
                    </td>
                    <td class="border-td">{{ number_format($payroll->rate_per_day, 2, '.', ',') }}</td>
                    <td class="border-td">{{ number_format($payroll->rate_per_hr, 2, '.', ',') }}</td>
                    <td class="border-td">{{ number_format($payroll->total, 2, '.', ',') }}</td>
                    @php
                    $currentUser = $payroll->user->formal_name();
                    if ($previousUser !== $currentUser) {
                    // If it's a different user, reset the total
                    $userTotal = $payroll->total;
                    } else {
                    // If it's the same user, add to the total
                    $userTotal += $payroll->total;
                    }

                    // Check if the next payroll has a different user
                    $nextUser = $index + 1 < count($payrolls) ? $payrolls[$index + 1]->user->formal_name() : null;
                        @endphp

                        @if ($nextUser !== $currentUser)
                        <td class="border-td" style="font-weight: bold;">{{ number_format($userTotal, 2, '.', ',') }}</td>
                        @else
                        <td class="border-td" style="font-weight: bold;"></td>
                        @endif

                        @php
                        $previousUser = $currentUser;
                        @endphp
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    <br>
</body>

</html>